services:
  - type: web
    name: pocket-lawyer-v15
    runtime: python
    repo: https://github.com/ergrhnb/pocket-lawyer-v15
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port \
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SETUPTOOLS_USE_DISTUTILS
        value: stdlib
